name: Gadgetgrlz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9996
title: Gadgetgrlz Props Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040603'
    - '#fffffd'
    - '#939089'
    - '#555549'
    - '#ce5028'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
